### ISSUE TITLE
Mac覆盖原文件后程序崩溃

### ISSUE THREAD

**Issue by zerone01y** [Cirn09/calibre-do-not-translate-my-path#1]
解压patch文档并将其中内容merge到原app后，无法打开calibre（程序崩溃）

**Comment by Cirn09** [comment]
首先确认一下补丁版本和 Calibre 版本是否一致。

我手里没有 mac 设备，你能帮忙提供以下崩溃日志之类的吗 https://support.apple.com/zh-cn/guide/console/cnsl664be99a/mac

**Comment by Cirn09** [comment]
报错是 Code Signature Invalid，是 patch 之后没有重新签名。

我没有 Mac 设备，你先试试自行给 `calibre-launcher.dylib` 重新签名（`codesign`）。

**Comment by Cirn09** [comment]
重写了一版，你先重装 Calibre，然后重新下载补丁覆盖试试

**Comment by avatarprophet** [comment]
LZ你好，在新版本（6.23）下面依然存在Mac版本报错的提示。我连续测试了6.22，6.21.都崩溃报错。
