### ISSUE TITLE
创建 patch 版安装包

### ISSUE THREAD

**Issue by Cirn09** [Cirn09/calibre-do-not-translate-my-path#10]
每次升级都要下载两份文件太麻烦了，补丁还要自己打太麻烦了

既然有了补丁，为什么不直接创建带补丁的安装包，一键完成呢

### 新增 patch 点

https://github.com/kovidgoyal/calibre/blob/506022b5aa000585fae296602d044fc532683647/src/calibre/gui2/update.py#L24-L32

- 检查更新：可以替换为本项目的 `CALIBRE_VERSION`，但是 `https://cirn09.github.io/calibre-do-not-translate-my-path/CALIBRE_VERSION` 实在有点长，可以用 CNAME+符号链接 缩一下 -> `https://calibre.cirn09.xyz/v`
- 下载链接：替换为本项目 latest release 页，通过空跳转页缩短 URL

### 重打包

- Linux: 就是压缩包，没有难点
- Windows: `msi2xml, xml2msi` 验证可重打包，但这套工具只有 Windows 版，action 需要添加 Windows 子 job 或者 wine。至于 `msitools` 工具集，我没搞懂 `msiextract` 之外的工具怎么用
- macOS: **尚不明确**：如何创建（修改） DMG，mac 对 DMG 的签名校验

**Comment by DawnLi-code** [comment]
Win和Linux不清楚，Mac个人认为不需要自动patch或者打包dmg，其实给个裸的python-lib.bypy.frozen文件最好，按说明路径自行手动patch，目前很多Mac的补丁也是这么做的。

现在是提供calibre.app压缩包文件夹，非常容易误导第一次使用patch(不认真看说明)的人。因为在Mac下.app结尾会显示成app文件，相信第一次使用的人不止我一个直接用patch误把calibre文件给覆盖了。而Mac下目录覆盖跟win逻辑不同，会清空目标目录原本的所有文件，整个替换为新的文件夹目录结构，所以patch直接覆盖calibre的app目录是会导致calibre无法运行的，目前打包的文件需要遏制住直接覆盖的冲动，一层层进去提取python-lib.bypy.frozen文件，再到calibre的app对应目录覆盖。

**Comment by hu3rror** [comment]
https://github.com/hu3rror/scoop-muggle/blob/master/bucket/calibre-normal-cjk.json

如果你使用 scoop 的话，可以参考我这个 manifest 进行检查更新一键更新补丁。原理是检测到补丁的版本更新的时候才更新官网的安装包，从而避免官网更新后补丁没有第一时间更新导致的问题

**Comment by Cirn09** [comment]
现在的 [7.1.0](https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/tag/v7.1.0) 已经加入了完整安装包

macOS 的 dmg 的重打包没找到合适的资料，安装 dmg 时会不会有签名校验也不了解，所以唯独 macOS 没有给出完整安装包，不过补丁已经根据 @DawnLi-code 的建议改成无文件夹压缩了，后续如果有相关资料的话可能会考虑添加 macOS 版完整安装包。

**Comment by hu3rror** [comment]
请问 `win-patch-backend+update-v7.1.0.zip` 和 `win-patch-backend-v7.1.0.zip` 区别是什么？

**Comment by Cirn09** [comment]
> 请问 `win-patch-backend+update-v7.1.0.zip` 和 `win-patch-backend-v7.1.0.zip` 区别是什么？


> v0: 最早的 patch 方案，现在应该已经没有对应的 release 了。同时 patch 了 bypy 和 Launcher，在 macOS 下会因为签名校验失败而无法使用。
> v1(backend): Patch 了 bypy 中的 backend.py，需要自行下载并替换文件。
> v2(backend+update): Patch 了 bypy 中的 backend.py 和 update.py，并重新打包了除 macOS 版之外的安装包。
使用补丁版的话，在新补丁发布时才会收到更新通知，需要自行下载原版安装包和补丁；使用安装包版的话，在新补丁发布时才会收到更新通知，并且只下载重打包的安装包就可以了。

**Comment by KervynH** [comment]
> 现在的 [7.1.0](https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/tag/v7.1.0) 已经加入了完整安装包
> 
> macOS 的 dmg 的重打包没找到合适的资料，安装 dmg 时会不会有签名校验也不了解，所以唯独 macOS 没有给出完整安装包，不过补丁已经根据 @DawnLi-code 的建议改成无文件夹压缩了，后续如果有相关资料的话可能会考虑添加 macOS 版完整安装包。

要是mac的patch版完整安装包不好搞，那能不能搞个用homebrew或者脚本安装的方法？这样一键就能patch
