### ISSUE TITLE
6.29版本替换后发送到设备还是拼音的问题

### ISSUE THREAD

**Issue by EricTLO** [Cirn09/calibre-do-not-translate-my-path#11]
6.29版本替换后发送到设备还是拼音的问题
软件已经压缩包上传
链接：https://pan.baidu.com/s/1WxqBVwnLOg8b8xa7l3VUFQ 
提取码：2mq8

**Comment by Cirn09** [comment]
可以了，快试试基于插件的 v3 版本吧
https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/tag/v3.0.0
