### ISSUE TITLE
Calibre7.0

### ISSUE THREAD

**Issue by CyanWoods** [Cirn09/calibre-do-not-translate-my-path#12]
你好，这两天calibre版本更新到7.0，自己试着fork了一下编译这个插件，发现编译的时候有点问题，请问您有没有针对7进行适配的计划。

**Comment by Cirn09** [comment]
甲流了，周末看看

**Comment by CyanWoods** [comment]
身体要紧，我可以回滚6.29的（笑

**Comment by doylecnn** [comment]
我只关心 win 版，因此下面以 win 版为例：
1. fork 
2. 修改main.py
2.1. 替换 `PFiles` 为 `PFiles64`
3. 修改 action.yaml，
  3.1. 注释116到119行，关于下载linux-arm64和mac 包的部分
  3.2 注释128到132行，关于arm64 和mac 解压缩的部分
  3.3 修改 155 行的代码 如下
`python main.py --os win --version $CALIBRE_VERSION`
  3.4 注释191到193行，关于我不关心的平台release 发布的部分
  3.5 替换 `PFiles` 为 `PFiles64`
  3.6 修改 164行，注释掉非win 平台文件的部分，仅保留 `calibre-win/PFiles64/Calibre2/app/bin/python-lib.bypy.frozen` 和 `calibre-win/PFiles64/Calibre2/app/bin/calibre-launcher.dll`
4. 执行action

顺利执行完成后可在 release 见到 patch-win-7.0.0.zip

**Comment by Cirn09** [comment]
原来只改了路径吗……

**Comment by doylecnn** [comment]
> 不对，对齐的断言没通过，不知道是我过度检查还是代码确实失效了，还是等周末看看吧

是的，注意到有个断言没过。但是看完log，win 的步骤是走完了，所以我就把 linux 和 mac 的部分都注释掉了，就“绕过”了。

**Comment by daopeng** [comment]
感谢作者，自从得知这个补丁，终于解决掉了烦人的中文书拼音路径问题。如果在6.29版本时修复了路径，升级到7后导入过英文书，再回滚到6.29版本，不会对Library的路径结构有影响吧，这时候再打上6.29的补丁，不需要对7下导入的英文书再做什么处理了吧？

**Comment by Cirn09** [comment]
> 感谢作者，自从得知这个补丁，终于解决掉了烦人的中文书拼音路径问题。如果在6.29版本时修复了路径，升级到7后导入过英文书，再回滚到6.29版本，不会对Library的路径结构有影响吧，这时候再打上6.29的补丁，不需要对7下导入的英文书再做什么处理了吧？

不影响

**Comment by daopeng** [comment]
> > 感谢作者，自从得知这个补丁，终于解决掉了烦人的中文书拼音路径问题。如果在6.29版本时修复了路径，升级到7后导入过英文书，再回滚到6.29版本，不会对Library的路径结构有影响吧，这时候再打上6.29的补丁，不需要对7下导入的英文书再做什么处理了吧？
> 
> 不影响
非常感谢！保重身体，早日康复～

**Comment by ernestyao** [comment]
不用管7.0了，今天7.1了
作者保重身体为先。自从中亚不能买书，Calibre用得频率也下降了
