### ISSUE TITLE
卡顿bug

### ISSUE THREAD

**Issue by Tobeprmn** [Cirn09/calibre-do-not-translate-my-path#15]
安装7.2完整安装包，点击首选项中的“获取用于增强calibre的插件”会出现卡顿的情况。
另外，我想请问下，在不卸载软件的情况下，覆盖安装7.2版本，软件设置会还原吗？

**Comment by Cirn09** [comment]
我觉得卡顿是因为网卡……

直接覆盖安装就可以了

**Comment by Tobeprmn** [comment]
好的，感谢
