### ISSUE TITLE
7.3.0版本全量包安装问题

### ISSUE THREAD

**Issue by Tobeprmn** [Cirn09/calibre-do-not-translate-my-path#16]
想安装在D:\Program Files (x86)，系统提示无权限（7.2版本也是使用你的全量包安装的）
![1](https://github.com/Cirn09/calibre-do-not-translate-my-path/assets/119318291/9028826f-ffb9-4387-ad53-5add8d69a5ea)

**Comment by Cirn09** [comment]
难以复现，我猜你 Calibre 没关

**Comment by Tobeprmn** [comment]
你好，重启电脑后在任务管理器确认无calibre后台后，再次安装，还是同样的问题，录屏以附件形式提交

https://github.com/Cirn09/calibre-do-not-translate-my-path/assets/119318291/acc24243-710f-4cbd-8c5b-63e7648d0f08

**Comment by Tobeprmn** [comment]
系统提示795d7.rbf文件无法安装

**Comment by Cirn09** [comment]
我不是清楚具体的原因，有如下尝试方向：
a. 弹窗时手动确认一下目标文件权限/删除文件后重试
b. 手动删掉 calibre 目录下所有文件（确保不要删掉任何数据文件、书库文件）后重试
c. 安装官方原版后覆盖安装 patch 版

**Comment by Tobeprmn** [comment]
是我的问题，官方安装包也是这个问题，不清楚什么原因，卸载重装了，卸载时只要不把配置文件删除就行

**Comment by Tobeprmn** [comment]
是我的问题，官方安装包也是这个问题，不清楚什么原因，卸载重装了，卸载时只要不把配置文件删除就行
