### ISSUE TITLE
请问这个补丁是否在版本升级时依然可用？

### ISSUE THREAD

**Issue by TsichiChang** [Cirn09/calibre-do-not-translate-my-path#2]
请问版本升级后是否需要重新下载补丁覆盖。

另外，如果我先使用了本插件把图书目录从拼音转成汉字，是否必须安装本补丁才能正确读取图书？

**Comment by Cirn09** [comment]
没试过，理论上应该是可以正确读取，新增图书还是英文。

正好今天刚更新了，明天 action 跑出补丁我试试

**Comment by Thinkbond** [comment]
可否请求适配一下5.44版？因为 macOS Catalina 最高只能支持到5.44（官方说法，不过我自己试了6.11也可），感激！

**Comment by Thinkbond** [comment]
> 可否请求适配一下5.44版？因为 macOS Catalina 最高只能支持到5.44（官方说法，不过我自己试了6.11也可），感激！

6.11.0 是可以用在 macOS Catalina 上的。

**Comment by Cirn09** [comment]
> 是否必须安装本补丁才能正确读取图书：没试过，理论上应该是可以正确读取，新增图书还是英文。正好今天刚更新了，明天 action 跑出补丁我试试

可以正确读取，新增图书还是英文
