### ISSUE TITLE
电子书元数据里标题过长时存在BUG

### ISSUE THREAD

**Issue by ZaneYork** [Cirn09/calibre-do-not-translate-my-path#23]
会报告路径过长：OSError: [Errno 36] 文件名过长
比如附件这本
[阿Q生命中的六个瞬间.zip](https://github.com/Cirn09/calibre-do-not-translate-my-path/files/14228429/Q.zip)

**Comment by Cirn09** [comment]
未复现，请自行搜索“解除 Windows 路径长度限制”

**Comment by ZaneYork** [comment]
> 未复现，请自行搜索“解除 Windows 路径长度限制”

这个限制是linux的文件系统的问题，在windows肯定不一定复现

**Comment by Cirn09** [comment]
Linux 问题请自行解决（
我这边没 Linux GUI 环境，原版 Calibre 会进行截断操作避免过长吗
