### ISSUE TITLE
能否支持将繁体改简体，类型目录名这些

### ISSUE THREAD

**Issue by JohnZp** [Cirn09/calibre-do-not-translate-my-path#26]

**Comment by Cirn09** [comment]
可行，但是困难

理论上可行，但是很麻烦。比较合适的方法就是增加模板字段，但是本项目的实现方式是有局限的，可以简单地实现减少代码长度的功能，对增加代码长度的功能是非常困难的。很明显，添加字段是增加代码长度的修改

https://github.com/Cirn09/calibre-do-not-translate-my-path/discussions/25#discussioncomment-8692789

**Comment by justemu** [comment]
这个繁体-简体转化的问题。不应该由这个补丁来实现。。

应该另外做一个元数据metadata 繁体转简体的插件。。。元数据时简体了，这个补丁只要保持元数据的信息就可以了。。

否则的话，可能还有需要简体转繁体的需求。。

把补丁做复杂了，反而不好维护！ 影响补丁及后续版本升级中的鲁棒性。

**Comment by JohnZp** [comment]
了解了, 我本地写脚本刷一遍吧,
