### ISSUE TITLE
文件名中的特殊字符，像半角的冒号，还是应该escape掉.

### ISSUE THREAD

**Issue by justemu** [Cirn09/calibre-do-not-translate-my-path#29]
如题：
我在使用时发现：如果元数据中的书籍名称如果带有不适合作为文件名路径的特殊字符。比如`:` 半角的冒号。这个补丁并不会去处理它。
比如linux系统中，文件名允许半角的冒号。但是windows系统就会无法识别，出现报错。

建议：
将linux、mac、windows中不允许作为文件名或路径的特殊保留字符，全部替换成下划线`_`。——johggong版本的calibre-web包就是用的这个处理方式，兼容性很好。只可惜他的calibre只更新到v5.53。

**Comment by Cirn09** [comment]
https://github.com/Cirn09/calibre-do-not-translate-my-path/blob/e7348430e75d54318fec2a4ddc16f4732dc881b8/patch_backend.py#L13-L34

特殊符号处理了，但是是 Windows 补丁只处理 Windows 特殊字符，*nix 只处理 *nix，混用时可能会出现问题
说明一下你的使用场景？

**Comment by justemu** [comment]
原来如此！您针对不同系统的版本，做了对应的特殊字符过滤！！太有心了！！！

我的问题出现在：
1. calibre通过kasm服务器部署在nas上。
2. 把nas上的calibre书库挂在在windows 电脑上。—— 这正是我坚持使用中文路径及文件名的原因。如果只是在服务器上，拼音之类的也无所谓。。。但是这样就遇到了不同操作系统下文件名路径的兼容性冲突问题。

建议：
还是按照各主流操作系统对特殊字符的集合，做一个统一的过滤器。。。这样可以增强系统的鲁棒性。。。避免像我这样场景的用户，也避免将来极端情况下做资料库维护的时候，用windows电脑无法装载linux系统下的书库的问题。

**Comment by Cirn09** [comment]
可以，周末我更新一下
当时没有考虑有这样的跨平台使用场景，而且实际上也没必要针对不同系统应用不同过滤

**Comment by RnYi** [comment]
我也是这个问题，书库在移动硬盘上，在Mac上转换了书名，Windows上访问就报错了，因为Windows不允许路径包含冒号。

**Comment by Cirn09** [comment]
已更改： https://github.com/Cirn09/calibre-do-not-translate-my-path/commit/40487b7afe1a6772b18fe4510254d9b2af861dc8

等下一版本补丁应该就可以修复这个问题了
等下一个版本补丁，在 *uix 系统上重新跑一次 readme 里提到的的刷新所有书籍路径的方法

**Comment by justemu** [comment]
先放一版 7.8.0_update1 出来吧。calibre的7.9.0还不知道要什么时候呢。

**Comment by Cirn09** [comment]
> 先放一版 7.8.0_update1 出来吧。calibre的7.9.0还不知道要什么时候呢。

7.9.0 就在今天
