### ISSUE TITLE
老版本能用吗？mac5.44.0

### ISSUE THREAD

**Issue by basekno** [Cirn09/calibre-do-not-translate-my-path#3]
如题。感谢

**Comment by Cirn09** [comment]
可以支持， https://github.com/snomiao/calibre-utf8-path 从 snomiao 开始不支持的版本到最新版都可以支持

从 https://github.com/Cirn09/calibre-do-not-translate-my-path/issues/2 来看，你也许可以先试试 6.11
.0


在 basekno ***@***.***>，2023年10月7日 00:40写道：

如题。感谢

**Comment by Cirn09** [comment]
你还是需要老版本补丁吗，需要的话我周末加一个手动 action 的选项
或者你自己 clone 跑一下也行
```
pip install -r ./requirestments.txt
python ./main.py --os man --version 5.44.0
```

**Comment by Thinkbond** [comment]
实测 6.11 无法使用补丁，如果能适配6.11，个人感激就不用再跑5.44啦。谢谢！

**Comment by Cirn09** [comment]
补丁版本需要和软件版本完全一致，确认一下是不是下错补丁了



在 Thinkbond ***@***.***>，2023年10月8日 08:54写道：

实测 6.11 无法使用补丁，如果能适配6.11，个人感激就不用再跑5.44啦。谢谢！

**Comment by Thinkbond** [comment]
抱歉是我描述有问题，之前说6.11可用是指Calibre的6.11.0可以在macOS Catalina下正常使用。
总结：求适配6.11.0，感谢。
---
刚才试着用clone后的命令自己跑6.11.0报错了。

**Comment by Cirn09** [comment]
噢噢，我以为我这已经有 6.11.0 的补丁了

在 Thinkbond ***@***.***>，2023年10月8日 09:08写道：

抱歉是我描述有问题，之前说6.11可用是指Calibre的6.11.0可以在macOS Catalina下正常使用。
总结：求适配6.11.0，感谢。

刚才试着用clone后的命令自己跑6.11.0报错了。

**Comment by Cirn09** [comment]
a. 官方最后一个支持旧版 macOS 的版本：[v5.44.0](https://download.calibre-ebook.com/5.44.0/calibre-5.44.0.dmg)，以及对应的补丁：[v5.44.0](https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v5.44.0/patch-mac-5.44.0.zip)

b. 实测可运行的版本：[v6.11.0](https://download.calibre-ebook.com/6.11.0/calibre-6.11.0.dmg)，以及对应的补丁：[v6.11.0](https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v6.11.0/patch-mac-6.11.0.zip)
