### ISSUE TITLE
Mac 替换文件后，calibre 打不开了

### ISSUE THREAD

**Issue by powersee** [Cirn09/calibre-do-not-translate-my-path#31]
下载 release 里 v7.9.0 的压缩包，得到 `python-lib.bypy.frozen`

粘贴到 `/Applications/calibre.app/Contents/Frameworks/plugins` 替换。

但是我 Mac 上的程序版本是 V6.15.1，替换之后呢，软件就打不开了。没有任何报错之类，APP 图标在 dock 栏跳一下，就没了。

**Comment by Cirn09** [comment]
补丁版本和软件版本需要完全一致

**Comment by powersee** [comment]
哦哦，原来如此，我重新下载了 6.15.1 的补丁，覆盖后可以打开了。感谢作者大大。
