### ISSUE TITLE
首选项-保存书籍至硬盘 设置路径不生效

### ISSUE THREAD

**Issue by liaobus** [Cirn09/calibre-do-not-translate-my-path#33]
默认：{authors}/{title}/{title}-{authors}
修改为：{title}/{title}-{authors}
修改保存后不生效，依然是默认的保存路径。
不知道什么原因，版本7.10

**Comment by Cirn09** [comment]
“保存书籍至硬盘” 这个功能是将书库中的文件导出到来时用的，不是书籍导入时的保存格式
