### ISSUE TITLE
有个建议功能：“发送到设备”这个保存到设备上的文件是拼音……

### ISSUE THREAD

**Issue by binswm** [Cirn09/calibre-do-not-translate-my-path#35]
目前“发送到设备”这个保存到设备上的文件是拼音……
这个能不能做到发送到设备直接就是中文啊

**Comment by motanzg** [comment]
支持

**Comment by Cirn09** [comment]
https://github.com/Cirn09/calibre-do-not-translate-my-path/discussions/25

**Comment by Cirn09** [comment]
可以了，快试试基于插件的 v3 版本吧
https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/tag/v3.0.0
