### ISSUE TITLE
建议补充说明一下macOS平台的使用方法

### ISSUE THREAD

**Issue by ernestyao** [Cirn09/calibre-do-not-translate-my-path#4]
macOS平台下，将解压的文件拖过去是“覆盖整个文件包”的动作，而不是仅替换单个文件，建议细化说明一下：

进入“应用程序”(/Applications)，右键点击`Calibre——显示包内容`，进入`Contents/Frameworks/plugins`(对应的完整路径是`/Applications/calibre.app/Contents/Frameworks/plugins`)。对解压出来的包，同样进入底层路径，找到`python-lib.bypy.frozen`，拷贝覆盖过去、关闭Finder窗口，正常打开Calibre即可。

**Comment by DawnLi-code** [comment]
哈哈，是的，我第一次就是直接覆盖，一顿操作猛如虎，根本没过脑，大小差异那么大都没注意看。
话说回来，这插件治好了我的强迫症啊😂

**Comment by Cirn09** [comment]
没用过 macOS，你可以整理一下，提个 PR；或者分步骤整理好，贴在这里

在 ernestyao ***@***.***>，2023年10月7日 09:30写道：

macOS平台下，将解压的文件拖过去是“覆盖整个文件包”的动作，而不是仅替换单个文件，建议细化说明一下：

进入“应用程序”(/Applications)，右键点击Calibre——显示包内容，进入Contents/Frameworks/plugins(对应的完整路径是/Applications/calibre.app/Contents/Frameworks/plugins)。对解压出来的包，同样进入底层路径，找到python-lib.bypy.frozen，拷贝覆盖过去、关闭Finder窗口，正常打开Calibre即可。
