### ISSUE TITLE
BUG：Debug模式下17-18.0版本没有转换中文路径

### ISSUE THREAD

**Issue by Heyastroom** [Cirn09/calibre-do-not-translate-my-path#40]
在debug模式下（解压了calibre soure 和calibre软件）运行calibre，添加电子书的时候未能生成中文路径/中文文件名，重新安装了暂未查找到问题的原因
calibre设置全初始化了还是未能解决问题

**Comment by Cirn09** [comment]
debug 模式下是直接执行源码的吧，本项目 patch 的是二进制
