### ISSUE TITLE
需求-calibre书库里面的书籍名称不带作者名

### ISSUE THREAD

**Issue by Nathalie-Annis** [Cirn09/calibre-do-not-translate-my-path#41]
calibre书库添加书籍之后的书籍名称格式是书名 - 作者名，这样在传到kindle里面的时候标题就会带个作者名，然后下面还会再显示一次作者的名称，这样重复了看着很难受，请问有没有办法只显示书籍名称呢？除了重新将calibre书库里面的书再保存到硬盘……

**Comment by Cirn09** [comment]
直接用 Calibre 发送到设备的功能吗？这个功能发送过去应该还是拼音啊

**Comment by Nathalie-Annis** [comment]
是拼音，但是书名后面有个作者名，比如红楼梦-曹雪芹，然后下面还会显示作者曹雪芹，重复的，看着很难受

**Comment by Nathalie-Annis** [comment]
是亚马逊的send to kindle功能，书名-作者名的格式会原封不动的传到书库里面去

**Comment by Nathalie-Annis** [comment]
是亚马逊的send to kindle功能，书名-作者名的格式会原封不动的传到kindle图书馆里面去
