### ISSUE TITLE
本地目录没问题了，但是邮件发送到设备的还是拼音

### ISSUE THREAD

**Issue by SakenW** [Cirn09/calibre-do-not-translate-my-path#6]

**Comment by Cirn09** [comment]
这是预期行为
首先是 calibre 这个功能的初衷，不知道目标设备是什么奇奇怪怪的设备、是否支持非 ASCII 字符集，当然现在也很难找到不支持中文的设备了。
然后是大部分阅读器设备，至少我用过的 kindle、文石都支持显示文档标题而不是文件名，除非你发送的是 txt 这种纯文本

在 Saken ***@***.***>，2023年10月10日 02:44写道：
