### ISSUE TITLE
win10 64位平台，ca版本6.28.1替换后无法启动软件

### ISSUE THREAD

**Issue by ms8great** [Cirn09/calibre-do-not-translate-my-path#7]
如题

**Comment by Cirn09** [comment]
相同环境，无法复现。
重新确认一下版本号、补丁版本号，换到一个空的书库再打补丁
依然无法解决的话可以把整个打完补丁的软件压缩发上来




在 ms8great ***@***.***>，2023年10月17日 15:33写道：

如题

**Comment by Cirn09** [comment]
缺少信息，补充信息后重开
